### ISSUE TITLE
"Unable to load AWS credentials from any provider in the chain"

### ISSUE THREAD

**Issue by dshechter** [SciLifeLab/NGI-RNAseq#171] opened 2017-11-27 17:29 UTC
I ran NGI-RNAseq using docker and it failed trying to get the genome files for STAR,. It did run fastqc, cutadapt, etc with no problem. Error below. I tried running it with a local fasta and gtf and it failed asking for a bed gene annotation file.

```
ERROR ~ Error executing process > 'star (null)'

Caused by:
Unable to load AWS credentials from any provider in the chain
```

Here's the command I ran:

```
nextflow run SciLifeLab/NGI-RNAseq -profile docker --singleEnd  \
--reads  '/data/NGS/NGS_Data/GEO/GSE85107_Armstrong2016_AML/fastq/SRR*fastq.gz' \
--genome GRCh37 --forward_stranded \
--outdir '/data/NGS/NGS_Data/GEO/GSE85107_Armstrong2016_AML/NGI-RNAseq.out' \
```

I'm running nextflow v 0.25.1 and docker v17.09.0-ce on CentOS 7.

Any thoughts? Since the AWS connection is in the docker VM, I shouldn't need any aws connection on my server, right? Thanks.

**Comment by ewels** [comment] 2017-11-28 15:48
Hi @dshechter,

Sorry to hear that you're having problems! There are a couple of things going on here...

#### 1) _I tried running it with a local fasta and gtf and it failed asking for a bed gene annotation file._

This is strange - the pipeline is designed to work with just a GTF file, creating a BED file if not supplied ([this code](https://github.com/SciLifeLab/NGI-RNAseq/blob/master/main.nf#L461-L478)). If this didn't happen then there must be a bug in the code. What was the exact error that you got?

#### 2) AWS Download
I've not seen this error before, but the AWS downloads have been annoyingly tricky (and difficult for us to test). If you're running the latest version of the NGI-RNAseq code then the pipeline should try to download the reference from `s3://ngi-igenomes/igenomes//Homo_sapiens/Ensembl/GRCh37/Sequence/STARIndex/`

I don't completely understand your question at the end - you'll need a web connection wherever the star process is running I think. Not 100% sure about this though, Nextflow handles the download natively and it could be that it runs this in the head process? But I'm pretty sure it happens in the job itself, so on the compute node. Could this explain the error?

Phil

**Comment by dshechter** [comment] 2017-11-29 05:38
1) Error is _No such variable: bed_genebody_coverage._ Here's the output of my runs with local fasta and BED files. Output of run:
 _N E X T F L O W  version 0.25.1
 Launching `SciLifeLab/NGI-RNAseq` [stoic_roentgen] - revision: 4e083df3c8 [master]
 =========================================
  NGI-RNAseq : RNA-Seq Best Practice v1.4dev
 =========================================
 Run Name       : stoic_roentgen
 Reads          : /data/NGS/NGS_Data/GEO/GSE85107_Armstrong2016_AML/fastq/SRR*fastq.gz
 Data Type      : Single-End
 Genome         : false
 Strandedness   : Forward
 Trim R1        : 0
 Trim R2        : 0
 Trim 3' R1     : 0
 Trim 3' R2     : 0
 Aligner        : STAR
 Fasta Ref      : /data/NGS/Stds/hs/gencode/GRCh38.primary_assembly.genome.fa
 GTF Annotation : /data/NGS/Stds/hs/gencode/gencode.v27.annotation.gtf
 Save Reference : No
 Save Trimmed   : No
 Save Intermeds : No
 Output dir     : /data/NGS/NGS_Data/GEO/GSE85107_Armstrong2016_AML/NGI-RNAseq.out
 Working dir    : /mnt/raid/NGS/NGS_Data/GEO/GSE85107_Armstrong2016_AML/fastq/work
 Container      : scilifelab/ngi-rnaseq:latest
 Pipeline Release: master
 Current home   : /home/david
 Current user   : david
 Current path   : /data/NGS/NGS_Data/GEO/GSE85107_Armstrong2016_AML/fastq
 R libraries    : false
 Script dir     : /home/david/.nextflow/assets/SciLifeLab/NGI-RNAseq
 Config Profile : docker
 =========================================
 [warm up] executor > local
 ERROR ~ No such variable: bed_genebody_coverage_


**2)** the script tried to pull those files from the S3 site as you note, but failed with that error. My question was do I personally need any AWS credentials on my own server, or S3 access tools? Or is that all embedded in the docker VM? Could there be some odd networking or permissions error for docker access to S3?

Thanks

**Comment by ewels** [comment] 2017-11-29 09:06
Great! Thanks for that - I'll try to replicate the bed12 error and fix that (it used to work so it must have broken somewhere along the way - I'll try to add a test to the CI script too to catch it).

On point 2) - the s3 pull should be handled by nextflow natively, see https://www.nextflow.io/docs/latest/amazons3.html So you can specify AWS credentials in your Nextflow config or in the usual aws access tools locations. No tools should be required in the docker container as the pull happens outside.

These s3 files should be public, so I'd hoped that no nextflow aws credentials would be necessary. Perhaps @pditommaso can shed some light on this? Can nextflow pull in files from s3 without any credentials if they're public?

Phil

**Comment by pditommaso** [comment] 2017-11-29 09:59
> Can nextflow pull in files from s3 without any credentials if they're public?

Yes. As long as you reference a specific public file and do not use other operations such navigate/list the directory structure

**Comment by ewels** [comment] 2017-11-29 10:33
Ah, that could be it - I think that this is a directory rather than a file:

```
s3://ngi-igenomes/igenomes//Homo_sapiens/Ensembl/GRCh37/Sequence/STARIndex/
```

**Comment by ewels** [comment] 2017-11-29 17:15
@pditommaso - any plans to make the nextflow s3 integration work with downloading directories? When specifying references like this it's kind of a pain to have to specify every single file..

**Comment by pditommaso** [comment] 2017-11-29 17:17
Already works like that, you can use glob pattern on a S3 path, tho you will need AWS credentials and permissions to list/navigate the folders

**Comment by ewels** [comment] 2017-11-29 17:19
ok, gotcha. So I need to add a `*` to the end of the reference paths then? Or will it work with the exact path that I pasted above (with aws credentials)?

**Comment by pditommaso** [comment] 2017-11-29 17:22
In the same way as you would do in a local path, just prefixing with `s3://`

**Comment by ewels** [comment] 2017-11-29 17:25
ok, so that's what I'm already doing then. So @dshechter - hopefully it should just work if you give Nextflow some AWS credentials.

Let me know if you still get the error!

**Comment by dshechter** [comment] 2017-11-30 20:26
Haven't had any time to play with this yet, but I don't have AWS credentials... just signed up and it's not obvious which permission policies to use within the AWS console. Suggestions?  

Then I put those access keys in the nextflow config file?

Any chance you can get the local bed file bug fixed, that's probably more useful on my end anyway so we can use whichever genome build we want.

Thanks!

**Comment by ewels** [comment] 2017-12-01 09:32
Ok, found the bed bug - there was a semicolon where there should have been a comma. Now fixed and merged, so the master branch should work 👍  Let me know if you have any more problems..

**Comment by dshechter** [comment] 2017-12-01 18:21
Well .. it generated the bed file, but now stalled for now obvious reason during the STAR mapping:

> Command output:
>   Dec 01 15:10:05 ..... started STAR run
>   Dec 01 15:10:05 ... starting to generate Genome files
>   Dec 01 15:12:30 ... starting to sort Suffix Array. This may take a long time...
>   Dec 01 15:12:56 ... sorting Suffix Array chunks and saving them to disk...
> 
> Command error:
>   .command.sh: line 9:    18 Killed                  STAR --runMode genomeGenerate --runThreadN 1 --sjdbGTFfile gencode.v27.annotation.gtf --sjdbOverhang 149 --genomeDir star/ --genomeFastaFiles GRCh38.primary_assembly.genome.fa
>   .command.run.1: line 99:    12 Terminated              nxf_trace "$pid" .command.trace
> 
> Work dir:
>   /mnt/raid/NGS/NGS_Data/GEO/GSE85107_Armstrong2016_AML/work/75/87bfdc2cd4f7b7e0df16430293b63f
> 
> Tip: when you have fixed the problem you can continue the execution appending to the nextflow command line the option `-resume`

and specific error in the .nextflow.log is:

> Dec-01 11:09:56.528 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'makeSTARindex (/data/NGS/Stds/hs/Homo_sapiens/E
> nsembl/GRCh37/Sequence/WholeGenomeFasta/genome.fa)'
> 
> Caused by:
>   Process `makeSTARindex (/data/NGS/Stds/hs/Homo_sapiens/Ensembl/GRCh37/Sequence/WholeGenomeFasta/genome.fa)` terminated with an error exit status (13
> 7)
> 
> Command executed:
> 
>   mkdir star
>   STAR \
>       --runMode genomeGenerate \
>       --runThreadN 1 \
>       --sjdbGTFfile genes.gtf \
>       --sjdbOverhang 149 \
>       --genomeDir star/ \
>       --genomeFastaFiles genome.fa
> 
> Command exit status:
>   137
> 

Tried it with the gencode fasta/gtf and ensembl fasta/gtf, both crashed at the same place. Thoughts? I don't see anything obvious. My machine has 128GB of RAM, most of that was available when I started the run. 

Another question: how can I set the number of threads used by the subprocesses (like STAR)?

**Comment by pditommaso** [comment] 2017-12-01 18:24
Exit code `137` is usually reported by a batch scheduler when it kills a job because is using too much memory

**Comment by dshechter** [comment] 2017-12-01 18:27
But I had more than enough free memory to run STAR - any idea how to solve this? STAR uses 40+GB for the mapping, but I have 3X available. Thanks.

**Comment by dshechter** [comment] 2017-12-01 20:50
I tried it with a precomputed STAR index and it still failed with error 137. Is there some kind of local docker flag to let it run with enough memory? Or something else, maybe with nextflow? I don't see why it's failing otherwise.  htop reported ~122GB free when I first ran the script.

**Comment by dshechter** [comment] 2017-12-01 22:03
Looks like the _docker.config_ file under _$HOME/.nextflow/assets/SciLifeLab/NGI-RNAseq/conf_ contained a line limiting the max RAM and CPU allocation. I increased that and it _seems_ to be working now...

**Comment by ewels** [comment] 2017-12-02 13:32
Thanks for the detailed feedback @dshechter! This kind of information is really helpful - our cluster returns `143` for out of memory error, so I'll add an `|| 137` to the script, then if processes fail for you then they should be resubmitted with double the memory requirement.

As you found - the pipeline comes with a config file which specifies how much memory should be requested for each type of process. The docker config that you're using has a default max memory limit of 16GB which was a bit stupid. This is probably left over from when I was running this on my laptop to prevent failures. I'll change the default back to 128GB.

We've recently refactored how this works and I haven't yet gotten around to documenting the feature, sorry about that. You can dynamically set the limits for the pipeline with the command line options if you don't want to make your own configs: `--max_memory`, `--max_cpus` and `--max_time`. Note that these are the ceiling limits for the requests, each process then requests its own specific amount up to that level. Your failed process was for the STAR genome build (not mapping), which by default requests 80GB memory. But if I add that error code at the top then it would then resubmit requesting 160GB (or the `max_memory` amount) if it failed due to lack of memory.

Number of subprocesses / cpus works the same as memory. `--max_cpus` and the process specific config. For example, the star index build is configured to request 10 cpus [here](https://github.com/SciLifeLab/NGI-RNAseq/blob/master/conf/base.config#L25). Note that it's usually up to the tool to make use of these. This particular process does this automatically by using whatever it's been granted [here](https://github.com/SciLifeLab/NGI-RNAseq/blob/master/main.nf#L386).

Ok, that was a bit of an essay sorry. Anyway, I'll push a change now then everything should work without any specific config files at your end. I'll also add some log lines to the top of the pipeline stdout which prints these values so that it's clearer.

Side note - code formatting in markdown is with backquotes, see [guide](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

Phil

**Comment by ewels** [comment] 2017-12-02 13:38
Ok, code written and waiting to be merged in #172 if the tests pass and I haven't broken anything.

**Comment by dshechter** [comment] 2017-12-03 04:38
So it ran most of the way through now and it crashed here:

> [d4/8ada40] Submitted process > multiqc (SRR3994136)
> [0a/359433] Submitted process > output_documentation (SRR3994136)
> ERROR ~ Error executing process > 'output_documentation (SRR3994136)'
> 
> Caused by:
>   Process `output_documentation (SRR3994136)` terminated with an error exit status (1)
> 
> Command executed:
> 
>   markdown_to_html.r /home/david/.nextflow/assets/SciLifeLab/NGI-RNAseq/docs/output.md results_description.html
> 
> Command exit status:
>   1
> 
> Command output:
>   (empty)
> 
> Command error:
>   Loading required package: markdown
>   Error in readLines(con) : cannot open the connection
>   Calls: markdownToHTML ... renderMarkdown -> tryCatch -> tryCatchList -> readLines
>   In addition: Warning message:
>   In readLines(con) :
>     cannot open file '/home/david/.nextflow/assets/SciLifeLab/NGI-RNAseq/docs/output.md': No such file or directory
>   Execution halted
>   .command.run.1: line 98:    12 Terminated              nxf_trace "$pid" .command.trace
> 

the output.md file is definitely there. Any thoughts on this error?

**Comment by ewels** [comment] 2017-12-04 08:21
Hmm, my first guess is that this is due to a docker mount problem - the file not being mounted properly so that the script can't find it. Not sure why we wouldn't get the same error when we run the pipeline in testing though.

@Hammarn - have we seen this before?

**Comment by Hammarn** [comment] 2017-12-04 08:36
Nope, I can't recall ever seeing this specific error.  It does strike me as odd that it was able to access all other R-libraries but not this one. Have you tried with just running it again? Maybe it was caused by some filesystem shenanigans?

**Comment by dshechter** [comment] 2017-12-07 14:29
I repeated that run, same error. I tried another dataset and it also produced the same error at the end. The 'output.md' file is definitely there.

> Command error:
>   Loading required package: markdown
>   Error in readLines(con) : cannot open the connection
>   Calls: markdownToHTML ... renderMarkdown -> tryCatch -> tryCatchList -> readLines
>   In addition: Warning message:
>   In readLines(con) :
>     **cannot open file '/home/david/.nextflow/assets/SciLifeLab/NGI-RNAseq/docs/output.md': No such file or directory**
>   Execution halted
>   .command.run.1: line 98:    12 Terminated              nxf_trace "$pid" .command.trace
>   Signal 15 (TERM) caught by ps (3.3.12).
>   ps:ps/display.c:66: please report this bug

Also, the STAR output BAM files are not showing up in the STAR folder. There are '*markDups.bam' files in the markDuplicates folder, but those *bai indecies are not from the markDups. Any idea what's going on there? This occurred in all of the runs.

**Comment by Hammarn** [comment] 2017-12-07 14:38
>Also, the STAR output BAM files are not showing up in the STAR folder. There are '*markDups.bam' files in the markDuplicates folder, but those *bai indecies are not from the markDups. Any idea what's going on there? This occurred in all of the runs.

That's expected behaviour, they take up extra space and you get the bam files from the `markDuplicates` step as well. I realized just now that the documentation isn't super clear about that - I'll update it. To have the `.bam` files form STAR saved you can use the following flag:
[--saveAlignedIntermediates] https://github.com/SciLifeLab/NGI-RNAseq/blob/master/docs/usage.md#--savealignedintermediates

Strange that the error persists. I guess it's good that it happens at the last step of the pipeline and that you get all of the results anyway.

**Comment by ewels** [comment] 2017-12-07 17:05
I'm pretty sure I know what's causing the missing file problem - I think it's a docker mount issue as I said before. I'll see if I can replicate and fix it now.

Phil

**Closed** 2017-12-11 14:39 UTC
Labels: bug

**Comment by ewels** [comment] 2017-12-11 14:57
Hi @dshechter,

We've just updated the pipeline with a change which should hopefully fix your last error (`cannot open file`). Please let us know how you get on! We can reopen this issue if you have any further problems.

Cheers,

Phil
